name: Deploy to Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.alexisboisset.cat
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: 21
        dangerous-clean-slate: false
        timeout: 120000
        state-name: .ftp-deploy-sync-state.json
        dry-run: false
        log-level: verbose
        security: loose
        retries: 3
        local-dir: ./
        server-dir: /
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.DS_Store
          **/env.php
          README.md
          .htaccess
          altres/**